version: '3.7'
# Removed subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1
# I had this:
# cat ~/.docker/config.json
# {"auths":{},"credsStore":"", "credsStore":"desktop","stackOrchestrator":"swarm"}
# I updated to this:
# {"auths":{},"credsStore":"","stackOrchestrator":"swarm"}
services:
  shopping-web-application:
    image: aniket/shopping-web-application-mysql:0.0.1-SNAPSHOT
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    restart: always
    depends_on: # Start the depends_on first
    - mysql
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: shopping
      RDS_USERNAME: todos-user
      RDS_PASSWORD: dummytodos
    networks:
    - shopping-web-application-network

  mysql:
    image: mysql:8.0.25
    ports:
    - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: todos-user
      MYSQL_PASSWORD: dummytodos
      MYSQL_DATABASE: shopping
    volumes:
    - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
    - shopping-web-application-network

# Volumes
volumes:
  mysql-dump:

networks:
   shopping-web-application-network:
     driver: bridge